<!--  
	Arquivo gerado pelo Build_Core 
	@author Maickon Rangel - maickon4developers@gmail.com
	Prodigio Framework - 2017
	View: init
-->

<h1>Prodígio Framework</h1>
<p>Um simples framework para projetos simples de iniciante.</p>
<p>Com o passar do tempo eu fui reunindo os utilitários que eu escrevia para me ajudar no desenvolvimento de minhas aplicações. Sei que o projeto é bem simples e nem se compara aos frameworks famosos por aí. Mas acredito que de alguma forma este simples framework consiga contribuir com a apredizado de alguém.</p>
<p>O projeto é baseado no modelo MVC e oferecer recursos como geração de código a partir de comandos no termial. Classes de abstração de dados, configuração de rotas e entre outras ferramentas que buscam ajudar no desenvolvimento do projeto.</p>

