
<div class="row" style="overflow: auto !important;">
	<div class="col-md-2">
		<h1>Índice</h1>
		<?php foreach ($sumary as $key => $value) { ?>
			<div>
				<a href="<?php echo URL_BASE; ?>document/show/<?php echo $value->id; ?>"><?php echo $value->title; ?></a> 
				|<a href="<?php echo URL_BASE; ?>document/edit/<?php echo $value->id; ?>">Editar</a>| 
			</div>
		<?php } ?>
			<div><a href="<?php echo URL_BASE; ?>document/form/">Add documentação</a></div>
	</div>

	<div class="col-md-10">
		<?php echo $show_document[0]->descript; ?>
	</div>
</div>