<html>
<head>
	<title><?php echo $this->meta_title; ?></title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="description" content="<?php echo $this->meta_description; ?>" />
	<meta name="keywords" content="<?php echo $this->meta_keywords; ?>" />
	<?php echo $this->css_files; ?>
</head>
<body>
	<nav class="navbar">
		<ul>
			<li><a href="<?php echo URL_BASE; ?>">Home</a></li>
			<li><a href="<?php echo URL_BASE; ?>rotas">Rotas</a></li>
			<li><a href="<?php echo URL_BASE; ?>documentacao">Documentação</a></li>
		</ul>
	</nav>
	<section class="body">
	<?php require_once $this->content(); ?>
	</section>
	<section class="footer">
		<p>Prodígio Framework - &copy <?php echo date("Y"); ?><br>Por Maickon Rangel</p>
	</section>
	
	<?php echo $this->js_files; ?>
</body>
</html>